package server

import (
	"bytes"
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gitcmd "go.kenn.io/kit/git/cmd"

	"go.kenn.io/forge/internal/apiclient/generated"
	"go.kenn.io/forge/internal/config"
	"go.kenn.io/forge/internal/db"
	ghclient "go.kenn.io/forge/internal/github"
	"go.kenn.io/forge/internal/server/workspaceapi"
	"go.kenn.io/forge/internal/testutil/dbtest"
	"go.kenn.io/forge/internal/workspace"
	"go.kenn.io/forge/internal/workspace/localruntime"
)

func TestLaunchWorkspaceRuntimeSessionPreparesAgentContext(t *testing.T) {
	t.Parallel()
	acquireRootWorkspaceGitSlot(t)
	assert := assert.New(t)
	require := require.New(t)
	d := dbtest.Open(t)
	worktree := initServerWorkspaceGitRepo(t)
	repoID := seedServerWorkspaceRepo(t, d)
	seedServerWorkspaceMR(t, d, repoID)

	ws := &db.Workspace{
		ID:              "ws-agent-context",
		Platform:        "github",
		PlatformHost:    "github.com",
		RepoOwner:       "acme",
		RepoName:        "widget",
		ItemType:        db.WorkspaceItemTypePullRequest,
		ItemNumber:      42,
		GitHeadRef:      "feature/widgets",
		WorkspaceBranch: "feature/widgets",
		WorktreePath:    worktree,
		TmuxSession:     "kenn-forge-ws-agent-context",
		TerminalBackend: "tmux",
		Status:          "ready",
	}
	require.NoError(d.InsertWorkspace(t.Context(), ws))
	seedServerWorkspaceLaunchSpec(t, d, ws, repoID)
	require.NoError(os.WriteFile(
		filepath.Join(worktree, "AGENTS.md"),
		[]byte("# Repository Agent Rules\n\nKeep this guidance.\n"), 0o644,
	))
	runServerWorkspaceTestGit(t, worktree, "add", "AGENTS.md")
	runServerWorkspaceTestGit(t, worktree, "commit", "-m", "add agent rules")
	staleMarked := "<!-- generated by kenn-forge; safe to delete; regenerated on agent launch -->\nstale\n"
	require.NoError(os.WriteFile(filepath.Join(worktree, "AGENTS.override.md"), []byte(staleMarked), 0o644))

	tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, t.TempDir(), filepath.Join(t.TempDir(), "tmux-record"))
	runtime := localruntime.NewManager(localruntime.Options{
		Targets: []localruntime.LaunchTarget{
			{
				Key:       "Codex yolo",
				Label:     "Codex",
				Kind:      localruntime.LaunchTargetAgent,
				Command:   []string{"/bin/sh", "-c", "exit 0"},
				Available: true,
			},
			{
				Key:       string(localruntime.LaunchTargetShell),
				Label:     "tmux",
				Kind:      localruntime.LaunchTargetShell,
				Command:   []string{tmuxPath},
				Available: true,
			},
		},
		TmuxCommand:             []string{tmuxPath},
		WrapAgentSessionsInTmux: true,
	})
	handler := workspaceapi.New(workspaceapi.Deps{
		DB:         d,
		Workspaces: workspace.NewManager(d, t.TempDir()),
		Runtime:    runtime,
	})
	input := &workspaceapi.LaunchWorkspaceRuntimeSessionInput{ID: ws.ID}
	input.Body.TargetKey = "Codex yolo"

	_, err := handler.LaunchWorkspaceRuntimeSession(t.Context(), input)
	require.NoError(err)

	override, err := os.ReadFile(filepath.Join(worktree, "AGENTS.override.md"))
	require.NoError(err)
	content := string(override)
	assert.Contains(content, "Source kind: pull request")
	assert.Contains(content, "PR: #42")
	assert.Contains(content, "Push branch: feature/widgets")
	assert.NotContains(content, "stale")
	assert.Less(
		strings.Index(content, "# Kenn Forge Workspace Context"),
		strings.Index(content, "# Repository Agent Rules"),
	)
	assert.True(strings.HasSuffix(content, "# Repository Agent Rules\n\nKeep this guidance.\n"))
	assert.NoFileExists(filepath.Join(worktree, "CLAUDE.local.md"))
	assertServerGitIgnored(t, worktree, "AGENTS.override.md")
	status := strings.TrimSpace(string(runServerWorkspaceTestGit(t, worktree, "status", "--porcelain")))
	assert.Empty(status)
}

func TestWorkspaceRuntimeLaunchWritesAgentContextE2E(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)
	dir := t.TempDir()
	tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, dir, filepath.Join(dir, "tmux-record"))
	agentPath := filepath.Join(dir, "helper-agent")
	require.NoError(os.WriteFile(agentPath, []byte("#!/bin/sh\nexit 0\n"), 0o755))
	cfg := &config.Config{
		Agents: []config.Agent{{Key: "codex", Label: "Codex", Command: []string{agentPath}}},
		Tmux:   config.Tmux{Command: []string{tmuxPath}},
	}
	client, _, _, _, _ := setupTestServerWithWorkspacesServer(t, cfg)
	ctx := context.Background()
	ws := createReadyWorkspace(t, ctx, client)

	assert.NoFileExists(filepath.Join(ws.WorktreePath, "AGENTS.override.md"))

	resp, err := client.HTTP.LaunchWorkspaceRuntimeSessionWithResponse(
		ctx, ws.Id,
		generated.LaunchWorkspaceRuntimeSessionInputBody{TargetKey: "codex"},
	)
	require.NoError(err)
	require.Equal(http.StatusOK, resp.StatusCode())

	agentsLocal, err := os.ReadFile(filepath.Join(ws.WorktreePath, "AGENTS.override.md"))
	require.NoError(err)
	assert.Contains(string(agentsLocal), "Source kind: pull request")
	assert.Contains(string(agentsLocal), "Push branch:")
	assert.NotContains(string(agentsLocal), "Working branch")
	assert.NoFileExists(filepath.Join(ws.WorktreePath, "CLAUDE.local.md"))
	assertServerGitIgnored(t, ws.WorktreePath, "AGENTS.override.md")
	status := strings.TrimSpace(string(runServerWorkspaceTestGit(
		t, ws.WorktreePath, "status", "--porcelain",
	)))
	assert.Empty(status)
}

func TestWorkspaceRuntimeLaunchRejectsUnsafeRepositoryAgentInstructionsE2E(t *testing.T) {
	tests := []struct {
		name      string
		entry     string
		forbidden string
	}{
		{name: "symlink", entry: "symlink", forbidden: "host secret"},
		{name: "oversized file", entry: "oversized", forbidden: strings.Repeat("x", 128)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert := assert.New(t)
			require := require.New(t)
			dir := t.TempDir()
			tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, dir, filepath.Join(dir, "tmux-record"))
			agentPath := filepath.Join(dir, "helper-agent")
			require.NoError(os.WriteFile(agentPath, []byte("#!/bin/sh\nexit 0\n"), 0o755))
			cfg := &config.Config{
				Agents: []config.Agent{{Key: "codex", Label: "Codex", Command: []string{agentPath}}},
				Tmux:   config.Tmux{Command: []string{tmuxPath}},
			}
			client, _, _, _, _ := setupTestServerWithWorkspacesServer(t, cfg)
			ctx := context.Background()
			ws := createReadyWorkspace(t, ctx, client)
			agentsPath := filepath.Join(ws.WorktreePath, "AGENTS.md")
			switch tt.entry {
			case "symlink":
				target := filepath.Join(t.TempDir(), "AGENTS.md")
				require.NoError(os.WriteFile(target, []byte(tt.forbidden), 0o644))
				require.NoError(os.Symlink(target, agentsPath))
			case "oversized":
				require.NoError(os.WriteFile(agentsPath, []byte(strings.Repeat("x", (1<<20)+1)), 0o644))
			}

			resp, err := client.HTTP.LaunchWorkspaceRuntimeSessionWithResponse(
				ctx, ws.Id,
				generated.LaunchWorkspaceRuntimeSessionInputBody{TargetKey: "codex"},
			)
			require.NoError(err)
			require.Equal(http.StatusOK, resp.StatusCode())

			override, err := os.ReadFile(filepath.Join(ws.WorktreePath, "AGENTS.override.md"))
			require.NoError(err)
			content := string(override)
			assert.Contains(content, "Source kind: pull request")
			assert.NotContains(content, tt.forbidden)
		})
	}
}

func TestWorkspaceRuntimeLaunchWritesIssueAndKataAgentContextE2E(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)
	dir := t.TempDir()
	database := dbtest.Open(t)
	syncer := ghclient.NewSyncer(nil, database, nil, nil, time.Minute, nil, nil)
	t.Cleanup(syncer.Stop)
	tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, dir, filepath.Join(dir, "tmux-record"))
	cfg := &config.Config{
		Tmux: config.Tmux{Command: []string{tmuxPath}},
		Agents: []config.Agent{{
			Key:     "codex",
			Label:   "Codex",
			Command: []string{"/bin/sh", "-c", "exit 0"},
		}},
	}
	srv := New(
		database, syncer, nil, "/", cfg,
		ServerOptions{
			WorktreeDir:                        filepath.Join(dir, "worktrees"),
			DisableWorkspaceBackgroundMonitors: true,
		},
	)
	t.Cleanup(func() { gracefulShutdown(t, srv) })

	issueWorktree := initServerWorkspaceGitRepo(t)
	seedIssue(t, database, "acme", "widget", 7, "open")
	issueWorkspace := &db.Workspace{
		ID: "ws-issue-context", Platform: "github", PlatformHost: "github.com",
		RepoOwner: "acme", RepoName: "widget",
		ItemType: db.WorkspaceItemTypeIssue, ItemNumber: 7,
		GitHeadRef: "kenn-forge/issue-7", WorkspaceBranch: "kenn-forge/issue-7",
		WorktreePath: issueWorktree, Status: "ready",
	}
	require.NoError(database.InsertWorkspace(t.Context(), issueWorkspace))
	issueRepo, err := database.GetRepoByIdentity(
		t.Context(), verifiedGitHubRepoIdentity("github.com", "acme", "widget"),
	)
	require.NoError(err)
	seedServerWorkspaceLaunchSpec(t, database, issueWorkspace, issueRepo.ID)

	kataWorktree := initServerWorkspaceGitRepo(t)
	require.NoError(database.InsertWorkspace(t.Context(), &db.Workspace{
		ID: "ws-kata-context", Platform: "github", PlatformHost: "github.com",
		RepoOwner: "acme", RepoName: "widget",
		ItemType: db.WorkspaceItemTypeKataTask,
		ItemKey: db.KataWorkspaceItemKey(db.WorkspaceKataMetadata{
			DaemonID: "home", ProjectUID: "project-1", IssueUID: "issue-kata-1",
		}),
		GitHeadRef: "kenn-forge/kata/task-123", WorkspaceBranch: "kenn-forge/kata/task-123",
		WorktreePath: kataWorktree, Status: "ready",
		KataMetadata: &db.WorkspaceKataMetadata{
			DaemonID: "home", ProjectUID: "project-1", ProjectName: "Widget",
			IssueUID: "issue-kata-1", ShortID: "KAT-12", Title: "Wire task context",
		},
	}))

	launch := func(workspaceID string) {
		t.Helper()
		req := httptest.NewRequest(
			http.MethodPost,
			"/api/v1/workspaces/"+workspaceID+"/runtime/sessions",
			bytes.NewBufferString(`{"target_key":"codex"}`),
		)
		req.Header.Set("Content-Type", "application/json")
		rec := httptest.NewRecorder()
		srv.ServeHTTP(rec, req)
		require.Equal(http.StatusOK, rec.Code, rec.Body.String())
	}

	launch("ws-issue-context")
	issueContext, err := os.ReadFile(filepath.Join(issueWorktree, "AGENTS.override.md"))
	require.NoError(err)
	assert.Contains(string(issueContext), "Source kind: provider issue")
	assert.Contains(string(issueContext), "Issue: #7")
	assert.NotContains(string(issueContext), "Test Issue")
	issueStatus := strings.TrimSpace(string(runServerWorkspaceTestGit(t, issueWorktree, "status", "--porcelain")))
	assert.Empty(issueStatus)

	// A pre-existing user-owned file makes launch succeed without touching
	// it: context delivery is silently skipped by design.
	userOwned := "# My own instructions\n"
	require.NoError(os.WriteFile(filepath.Join(kataWorktree, "AGENTS.override.md"), []byte(userOwned), 0o644))
	launch("ws-kata-context")
	preserved, err := os.ReadFile(filepath.Join(kataWorktree, "AGENTS.override.md"))
	require.NoError(err)
	require.Equal(userOwned, string(preserved))
	require.NoError(os.Remove(filepath.Join(kataWorktree, "AGENTS.override.md")))

	launch("ws-kata-context")
	kataContext, err := os.ReadFile(filepath.Join(kataWorktree, "AGENTS.override.md"))
	require.NoError(err)
	assert.Contains(string(kataContext), "Source kind: Kata task")
	assert.Contains(string(kataContext), "Kata daemon: home")
	assert.Contains(string(kataContext), "Issue UID: issue-kata-1")
	assert.Contains(string(kataContext), "Short ID: KAT-12")
	assert.Contains(string(kataContext), "<untrusted-source-text>Wire task context</untrusted-source-text>")
	kataStatus := strings.TrimSpace(string(runServerWorkspaceTestGit(t, kataWorktree, "status", "--porcelain")))
	assert.Empty(kataStatus)
}

func seedServerWorkspaceRepo(t *testing.T, d *db.DB) int64 {
	t.Helper()
	repoID, err := d.UpsertRepo(t.Context(), verifiedGitHubRepoIdentity("github.com", "acme", "widget"))
	require.NoError(t, err)
	seedRepoLaunchMetadata(t, d, repoID)
	return repoID
}

func seedServerWorkspaceLaunchSpec(
	t *testing.T, database *db.DB, ws *db.Workspace, repoID int64,
) {
	t.Helper()
	repo, err := database.GetRepoByID(t.Context(), repoID)
	require.NoError(t, err)
	require.NotNil(t, repo)
	issuedAt := time.Now().UTC()
	spec := db.WorkspaceLaunchSpec{
		Version: db.WorkspaceLaunchSpecVersion,
		Repository: db.WorkspaceLaunchRepository{
			Provider: repo.Platform, PlatformHost: repo.PlatformHost,
			PlatformRepoID: repo.PlatformRepoID, Owner: repo.Owner, Name: repo.Name,
			CloneURL: repo.CloneURL, DefaultBranch: repo.DefaultBranch,
		},
		ItemType: ws.ItemType, ItemNumber: ws.ItemNumber,
		ItemKey: strconv.Itoa(ws.ItemNumber), GitHeadRef: ws.GitHeadRef,
		SourceVisible: true, IssuedAt: issuedAt,
		SourceVisibleUntil: issuedAt.Add(db.WorkspaceLaunchSpecVisibilityLease),
	}
	if ws.ItemType == db.WorkspaceItemTypePullRequest {
		pull, readErr := database.GetMergeRequestByRepoIDAndNumber(
			t.Context(), repoID, ws.ItemNumber,
		)
		require.NoError(t, readErr)
		require.NotNil(t, pull)
		spec.Pull = &db.WorkspaceLaunchPull{
			HeadBranch: pull.HeadBranch, HeadRepoKind: "same_repo",
			SnapshotRevision: pull.SnapshotRevision,
		}
	}
	require.NoError(t, database.PutWorkspaceLaunchSpec(t.Context(), ws.ID, spec))
}

func seedServerWorkspaceMR(t *testing.T, d *db.DB, repoID int64) {
	t.Helper()
	now := time.Date(2024, 6, 1, 12, 0, 0, 0, time.UTC)
	_, err := d.UpsertMergeRequest(t.Context(), &db.MergeRequest{
		RepoID:         repoID,
		PlatformID:     4200,
		Number:         42,
		URL:            "https://github.com/acme/widget/pull/42",
		Title:          "Launch context",
		Author:         "author",
		State:          "open",
		HeadBranch:     "feature/widgets",
		BaseBranch:     "main",
		CreatedAt:      now,
		UpdatedAt:      now,
		LastActivityAt: now,
	})
	require.NoError(t, err)
}

func initServerWorkspaceGitRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	runServerWorkspaceTestGit(t, dir, "init", "--initial-branch=main")
	runServerWorkspaceTestGit(t, dir, "config", "user.email", "test@example.test")
	runServerWorkspaceTestGit(t, dir, "config", "user.name", "Test User")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "README.md"), []byte("# Test\n"), 0o644))
	runServerWorkspaceTestGit(t, dir, "add", "README.md")
	runServerWorkspaceTestGit(t, dir, "commit", "-m", "initial")
	return dir
}

func runServerWorkspaceTestGit(t *testing.T, dir string, args ...string) []byte {
	t.Helper()
	out, stderr, err := gitcmd.New().Run(t.Context(), dir, nil, args...)
	require.NoError(t, err, "git %v failed: %s%s", args, out, stderr)
	return out
}

func assertServerGitIgnored(t *testing.T, dir, rel string) {
	t.Helper()
	runServerWorkspaceTestGit(t, dir, "check-ignore", "--quiet", "--", rel)
}
