DROP TRIGGER forge_notification_ack_admission_clear;
DROP TRIGGER forge_notification_ack_admission_update;
DROP TRIGGER forge_notification_ack_admission_insert;
DROP TABLE forge_notification_ack_admissions;
DROP TABLE forge_node_preparation_seals;
DROP TABLE forge_node_preparation_receipts;
DROP TABLE forge_node_preparation;
DROP TABLE forge_workspace_launch_specs;
