package workspaceapi

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humago"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.kenn.io/forge/internal/agentactivity"
	"go.kenn.io/forge/internal/db"
	"go.kenn.io/forge/internal/providerplane"
	"go.kenn.io/forge/internal/testutil/dbtest"
	"go.kenn.io/forge/internal/workspace"
)

func TestReceiveAgentHookRecordsActivityAndGeneratesClaudeContext(t *testing.T) {
	t.Parallel()
	require := require.New(t)
	assert := assert.New(t)
	database := dbtest.Open(t)
	worktree := t.TempDir()
	require.NoError(database.InsertWorkspace(t.Context(), &db.Workspace{
		ID:              "ws-agent-hook",
		Platform:        "github",
		PlatformHost:    "github.com",
		RepoOwner:       "acme",
		RepoName:        "widget",
		ItemType:        db.WorkspaceItemTypeIssue,
		ItemNumber:      42,
		GitHeadRef:      "kenn-forge/issue-42",
		WorkspaceBranch: "kenn-forge/issue-42",
		WorktreePath:    worktree,
		TmuxSession:     "kenn-forge-ws-agent-hook",
		Status:          "ready",
	}))
	require.NoError(database.PutWorkspaceLaunchSpec(
		t.Context(), "ws-agent-hook", workspaceLaunchSpecForRequest(
			providerplane.WorkspaceLaunchRequest{
				Repository: providerplane.RepositoryRoute{
					Provider: "github", PlatformHost: "github.com",
					Owner: "acme", Name: "widget",
				},
				ItemType: db.WorkspaceItemTypeIssue, ItemNumber: 42,
				ItemKey: "42", GitHeadRef: "kenn-forge/issue-42",
			},
			time.Now().UTC(),
		),
	))
	require.NoError(os.WriteFile(
		filepath.Join(worktree, "CLAUDE.local.md"),
		[]byte("private user context that must never be forwarded\n"), 0o644,
	))
	activity := agentactivity.NewStore(t.TempDir())
	handler := New(Deps{
		DB:            database,
		Workspaces:    workspace.NewManager(database, t.TempDir()),
		AgentActivity: activity,
	})
	mux := http.NewServeMux()
	api := humago.NewWithPrefix(
		mux, "/api/v1", huma.DefaultConfig("workspace test", "1"),
	)
	handler.Register(api)

	post := func(agent, runtimeKey string, payload map[string]any) *httptest.ResponseRecorder {
		t.Helper()
		body, err := json.Marshal(payload)
		require.NoError(err)
		req := httptest.NewRequest(
			http.MethodPost, "/api/v1/agent-hooks/"+agent,
			bytes.NewReader(body),
		)
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("X-Kenn-Forge-Runtime-Session-Key", runtimeKey)
		rec := httptest.NewRecorder()
		mux.ServeHTTP(rec, req)
		return rec
	}

	working := post("gemini", "runtime-1", map[string]any{
		"session_id":      "agent-1",
		"cwd":             worktree,
		"hook_event_name": "UserPromptSubmit",
		"transcript_path": "/tmp/agent-transcript.jsonl",
		"permission_mode": "default",
	})
	require.Equal(http.StatusOK, working.Code, working.Body.String())
	snapshot, ok := activity.SnapshotForWorkspace(worktree, []string{"runtime-1"})
	require.True(ok)
	assert.Equal(agentactivity.StateWorking, snapshot.State)

	started := post("claude", "runtime-1", map[string]any{
		"session_id":      "agent-1",
		"cwd":             worktree,
		"hook_event_name": "SessionStart",
		"source":          "startup",
	})
	require.Equal(http.StatusOK, started.Code, started.Body.String())
	var response struct {
		HookOutput *struct {
			HookSpecificOutput struct {
				HookEventName     string `json:"hookEventName"`
				AdditionalContext string `json:"additionalContext"`
			} `json:"hookSpecificOutput"`
		} `json:"hook_output"`
	}
	require.NoError(json.NewDecoder(started.Body).Decode(&response))
	require.NotNil(response.HookOutput)
	assert.Equal("SessionStart", response.HookOutput.HookSpecificOutput.HookEventName)
	assert.Contains(response.HookOutput.HookSpecificOutput.AdditionalContext, "Workspace ID: ws-agent-hook")
	assert.Contains(response.HookOutput.HookSpecificOutput.AdditionalContext, "Issue: #42")
	assert.NotContains(response.HookOutput.HookSpecificOutput.AdditionalContext, "private user context")
	assert.NotContains(response.HookOutput.HookSpecificOutput.AdditionalContext, "<!-- generated by kenn-forge")
}
