ARG GITLAB_BASE_IMAGE=gitlab/gitlab-ce:19.3.0-ce.0
FROM ${GITLAB_BASE_IMAGE}

COPY bootstrap.sh wait.sh /opt/kenn-forge/gitlab-fixture/
COPY fixture-entrypoint.sh /usr/local/bin/kenn-forge-gitlab-fixture-entrypoint

RUN chmod +x \
    /opt/kenn-forge/gitlab-fixture/bootstrap.sh \
    /opt/kenn-forge/gitlab-fixture/wait.sh \
    /usr/local/bin/kenn-forge-gitlab-fixture-entrypoint

CMD ["/usr/local/bin/kenn-forge-gitlab-fixture-entrypoint"]
